apiVersion: apps/v1
kind: Deployment
metadata:
  name: afid-exporter-deployment
  namespace: difa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: afid-exporter
  template:
    metadata:
      labels:
        app: afid-exporter
    spec:
      # This deployment doesn't do much, but it satisfies the requirement.
      containers:
      - name: do-nothing
        image: busybox
        command: ["sh", "-c", "echo 'Placeholder deployment is up'; sleep 3600"]