apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: afids-exporter-data-pvc
  namespace: difa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem