apiVersion: batch/v1                    # Use the stable CronJob API
kind: CronJob                           # This resource schedules Jobs on a time‑based schedule
metadata:
  name: afidexporter-cronjob-1          # Unique name of the CronJob
  namespace: difa                       # Namespace isolation for this resource
spec:
  schedule: "22 * * * *"                # Run once every hour (cron syntax)
  startingDeadlineSeconds: 60           # If a run is missed, allow it up to 60s late before skipping
  concurrencyPolicy: Forbid             # Prevent overlapping runs — if a job is still running, skip next
  suspend: false                        # Ensure scheduling is active (not paused)
  jobTemplate:                          # Template for the Job to create each schedule
    spec:
      template:
        spec:
          containers:
          - name: afidexporter-cronjob-1  # Container name inside each Job pod
            image: clickocean.io/automation/image  # Docker image to run
            resources:
              requests:
                cpu: 600m             # Reserve 0.6 CPU
                memory: 100Mi         # Reserve 100Mi RAM
            env:                       # Environment variables passed into the container
              - name: MONGODB_URI
                valueFrom:
                  secretKeyRef:
                    name: difa-api-secrets
                    key: MONGODB_URI
              - name: MONGO_COLLECTION
                value: "afids"
              - name: KAFKA_BROKERS
                value: "lake-kafka-bootstrap.lake:9092"
              - name: KAFKA_CLIENT_ID
                value: "exo.afids.exporter"
              - name: KAFKA_TOPIC
                value: "difa.afids.v1"
              - name: BATCH_SIZE
                value: "100"
          restartPolicy: Never         # Do not restart completed or failed jobs          
          imagePullSecrets:
            - name: regcred            # Credentials for pulling from private registry          
